### ISSUE TITLE
Remove job_detail - Add 'jobrelation' detail to org

### ISSUE THREAD

**Issue by Evidlo** [purdue-epics-ims/boilerconnect#34]
A single Job applies to multiple organizations.  An org shouldn't be able to see what other orgs a Job has been sent to.

Instead, we should replace job_detail with jobrelation_detail, which provides information specific to a Job-Organization pair.  The url would be something like /organization/1/job/1

This is also a necessity if we are going to implement some kind of job negotiation system (Orgs can comment on Jobs before accepting the Job.)
## Todo
- [ ] - rename `JobRelation` -> `Job`, `Job` -> `JobRequest`
- [ ] - add perms to Job
- [ ] - update edit_job to work with new `Job`
- [ ] - update create_job to work with new `Job`
- [x] - update job_detail to work with new `Job`
